const gifts = [
  "mucho dinero",
  "un hermoso auto",
  "carbón",
  "un cactus navideño",
  "una taza con un agujero",
  "un calcetín usado",
  "un viaje a parís",
  "un perro robot bailarín",
  "un libro sobre cómo ser aburrido",
  "un aguacate maduro",
  "una bicicleta sin llantas",
  "un playstation 6 (de cartón)",
  "una bufanda tejida por tu tía",
  "una colección de piedras",
  "una suscripción a un gimnasio (¿indirecta?)",
  "un control remoto sin pilas",
  "un conejo saltarín",
  "un reloj que siempre marca las 3:00 am",
  "una caja vacía",
  "una colección de memes impresos",
  "un baño portátil",
  "un robot que canta villancicos todo el día",
  "una selfie con santa claus",
  "un colchón inflable que se desinfla solo",
  "una maceta con hierbas aromáticas",
  "un boleto de lotería no ganador",
  "una sartén de hierro",
  "un espejo que te da cumplidos",
  "una suscripción a clases de canto",
  "una planta carnívora",
  "un sombrero con luces led",
  "un kit para hacer slime",
  "un cargador de teléfono universal (¡pero no funciona!)",
  "un kit de magia incompleto",
  "un globo terráqueo pixelado",
  "una lámpara de lava",
  "una cobija con la cara de tu perro",
  "un álbum de fotos de desconocidos",
  "un boleto al espacio (en tus sueños)",
  "un vale por una hamburguesa",
  "un paraguas que gotea",
  "un anillo de plástico",
  "un diccionario de emojis",
  "un set de maquillaje para payasos",
  "una pelota de playa en invierno",
  "un karaoke portátil",
  "un teclado que brilla en la oscuridad",
  "un curso para aprender a ladrar",
  "un ventilador de mano (¡en diciembre!)",
  "un cargador solar en días nublados",
  "una máquina para hacer algodón de azúcar",
  "un montón de confeti",
  "unas tijeras para zurdos (¡pero eres diestro!)",
  "un rompecabezas de 5000 piezas (¡sin bordes!)",
  "un perfume con olor a tacos",
  "una réplica de la torre eiffel",
  "un reloj de arena de 2 horas",
  "unas pantuflas con forma de gato",
  "un chaleco navideño que canta",
  "una caja de chocolates... derretidos",
  "un juego de té para niños",
  "un diploma de mejor persona",
  "una piedra pintada a mano",
  "una serpiente de juguete",
  "un calendario de memes",
  "una mini aspiradora para el escritorio",
  "un osito de peluche gigante",
  "un tambor para tu sobrino pequeño (los papás lo odiarán)",
  "unas gafas para ver el futuro (spoiler: no funciona)",
  "unos audífonos inalámbricos... con cables",
  "unas baterías que nunca cargan",
  "un álbum de stickers",
  "un disfraz de árbol de navidad",
  "un kit de cocina molecular",
  "un juego de mesa aburridísimo",
  "una linterna solar",
  "un masajeador de pies eléctrico",
  "unas crocs personalizadas",
  "unas medias con tu cara estampada",
  "unas gafas de sol para interiores",
  "un suéter que pica",
  "una caja llena de cajas",
  "unas velas aromáticas con olor a cebolla",
  "unas pesas de 1 kg",
  "un collar para tu perro... que no tienes",
  "unas galletas hechas por un niño de 3 años",
  "una espada láser (de juguete)",
  "un disfraz de reno",
  "unas bolas de nieve falsas",
  "unas sandalias en pleno invierno",
  "un gps que solo habla en latín",
  "una réplica de un trofeo de fútbol",
  "un usb con 1 mb de almacenamiento",
  "unas orejas de elfo",
];

export function randomGift() {
  const random = Math.floor(Math.random() * gifts.length);
  return gifts[random];
}
