import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <Link href={"/santa-claus"}>Santa Claus</Link>
      <Link href={"/new-year"}>Año nuevo</Link>
    </div>
  );
}
