import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  //const [name, setName] = useState("");
  //const [gift, setGift] = useState("");
  return (
    <div>
      <Link href={"/santa-claus"}>Santa Claus</Link>
      <p>año nuevo</p>
    </div>
  );
}
